name: Build and deploy Delphi with aws S3

on: 
  push:
    branches: [ master ]

jobs:
  test:
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
        
      - name: Test unit
        run: c:\lixo\build.bat Test TesteUnitarioProjeto.dproj
    
  build:
    needs: test
    runs-on: [self-hosted, Windows, X64]
    steps:
      - uses: actions/checkout@v2
      
      - name: Build aplication
        run: c:\lixo\build.bat . InensiveDelphi2020.dproj
