on: [push]

jobs:
  hello_world_job:
    runs-on: [self-hosted, Windows, X64]
    name: A job to say hello
    steps:
      - uses: actions/checkout@master
    steps:
      - name: Executa bat
        run: c:\lixo\executa.bat
