on: [push]

jobs:
  setup:
    runs-on: [self-hosted, Windows, X64]
    name: Full Cycle intensive Delphi

    steps:
      - name: Teste unitario
        run: call "C:\Program Files (x86)\Embarcadero\Studio\20.0\bin\rsvars.bat" && msbuild InensiveDelphi2020.dproj
