on: [push]

jobs:
  setup:
    runs-on: [self-hosted, Windows, X64]
    name: Full Cycle intensive Delphi

    steps:
      - uses: actions/checkout@v2
        
      - name: Teste unitario
        run: c:\lixo\build.bat $GITHUB_WORKFLOW InensiveDelphi2020.dproj
