name: MasterCI

on:
  push:
    branches: [ master ]
    
jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Deploy
    
    steps:
    - uses: actions/checkout@v2
      
    - name: Publish
      uses: alepmedeiros/scp-deploy@v1
      with:
        src: .
        host: 54.221.5.196
        remote: /home/ubuntu/sws_eduzzwebhook
        port: 22
        user: ubuntu
        key: ${{ secrets.SSH_KEY }}
